Repository IOTSenserSensei/T-IOT-902_sensorSensei, pull requests merged in 2024-04, with the labels that each got.

#26 Feat/ci
  .github/workflows/api_build.yaml
  .github/workflows/build.yaml
  .github/workflows/iot_build.yaml
  .github/workflows/mirroring.yaml
  .gitignore
  api/Cargo.lock
  api/Cargo.toml
  api/src/main.rs
  iot/Doxyfile
  iot/README.md
  iot/config.ini
  iot/docs/README.md
  iot/docs/doxygen/.gitkeep
  iot/include/README
  iot/lib/Emitter/library.json
  iot/lib/README
  iot/platformio.ini
  iot/secrets_exemple.ini
  iot/src/emitter/main.cpp
  iot/src/receptor/main.cpp
  iot/test/test.cpp
  src/receptor/main.cpp
  test/README
Labels: CI/CD, à merger

#37 #35 #33: Ajout de l'analyse static de code
  .github/workflows/api_build.yaml
  .github/workflows/iot_build.yaml
  iot/platformio.ini
Labels: CI/CD, à merger

#31 #7 [DOC] Added documentation on GY-BMP280 (BMP280)
  docs/GY-BMP280.md
Labels: documentation, à merger

#38 Ajouts documentation du choix des composants
  .gitignore
  docs/COMPONENTS_CHOICES.md
Labels: documentation
